# SELECT BB.AUTHOR_ID,	A.AUTHOR_NAME,	BB.CATEGORY,	BB.TOTAL*BB.PRICE AS TOTAL_SALES
# FROM (
# SELECT S.BOOK_ID, SUM(SALES) AS TOTAL, B.AUTHOR_ID, B.CATEGORY, B.PRICE
# FROM BOOK_SALES S
# JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# WHERE SALES_DATE LIKE "2022-01%"
# GROUP BY BOOK_ID
#     ) BB
#     JOIN AUTHOR A ON BB.AUTHOR_ID =A.AUTHOR_ID
#     ORDER BY 1,3 DESC


SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES* B.PRICE)  AS TOTAL_PRICE 
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY 1, 3 DESC