SELECT *
FROM (
    SELECT  
        B.CAR_ID, 
        P.CAR_TYPE, 
        FLOOR((B.FEE * 30) * (100 - DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    JOIN (
        SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE AS FEE
        FROM CAR_RENTAL_COMPANY_CAR C
        WHERE C.CAR_TYPE IN ('세단', 'SUV')
          AND C.CAR_ID NOT IN (
              SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
          )
    ) B ON P.CAR_TYPE = B.CAR_TYPE
    WHERE P.DURATION_TYPE = '30일 이상'
) A
WHERE A.FEE >= 500000 AND A.FEE < 2000000
ORDER BY A.FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
