# SELECT P.PRODUCT_ID,	P.PRODUCT_NAME, 
# FROM FOOD_PRODUCT P
# JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
# GROUP BY PRODUCT_ID

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.TOTAL*P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID) O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 3 DESC, 1


