# SELECT F.FLAVOR
# FROM FIRST_HALF F
# JOIN JULY J ON F.SHIPMENT_ID = J.SHIPMENT_ID
# GROUP BY F.FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER)+ SUM(J.TOTAL_ORDER) DESC
# LIMIT 3

SELECT J.FLAVOR
FROM JULY J
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
        FROM FIRST_HALF
        GROUP BY FLAVOR
      ) H ON H.FLAVOR = J.FLAVOR
      GROUP BY J.FLAVOR
      ORDER BY H.TOTAL + SUM(J.TOTAL_ORDER) DESC
      LIMIT 3



