SELECT A.EMP_NO, A.EMP_NAME, A.GRADE,
CASE
WHEN A.GRADE='S' THEN A.SAL*20/100
WHEN A.GRADE='A' THEN A.SAL*15/100
WHEN A.GRADE='B' THEN A.SAL*10/100
ELSE 0
END AS BONUS
FROM ( 
SELECT G.EMP_NO, E.EMP_NAME, CASE
WHEN AVG(SCORE) >= 96 THEN 'S'
WHEN AVG(SCORE) >= 90 THEN 'A'
WHEN AVG(SCORE) >= 80 THEN 'B'
ELSE 'C'
END AS GRADE, SAL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
GROUP BY EMP_NO
) A



