SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") as REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN (
SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW
WHERE MEMBER_ID = (
SELECT MEMBER_ID 
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID)DESC
LIMIT 1
)
) R ON R.MEMBER_ID = P.MEMBER_ID
order by 3,2




